[general]
import = [
    "~/.config/alacritty/themes/catppuccin-frappe.toml"
]

[env]
  TERM = "xterm-256color"

[font]
    size = 12

[font.normal]
    family = "MesloLGL Nerd Font"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"

[window]
opacity = 0.85
blur = true

