source "$HOME/.config/shell/settings.sh"

source "$XDG_CONFIG_HOME/shell/external.sh"
source "$XDG_CONFIG_HOME/shell/functions.sh"
source "$XDG_CONFIG_HOME/shell/bootstrap.sh"
source "$XDG_CONFIG_HOME/shell/aliases.sh"

if [ -f "$HOME/.bashrc_local_before" ]; then
    source "$HOME/.bashrc_local_before"
fi

source "$XDG_CONFIG_HOME/bash/functions.bash"
source "$XDG_CONFIG_HOME/bash/settings.bash"

if [ -f "$HOME/.bashrc_local_after" ]; then
    source "$HOME/.bashrc_local_after"
fi

if [ -f "$HOME/.bashrc_private" ]; then
    source "$HOME/.bashrc_private"
fi
