name: CI
on:
  push:
  pull_request:
jobs:
  install-dotifles:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          SHOULD_INSTALL_WORK_PROFILE=true ./install
  install-dotifles-work-profile:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          SHOULD_INSTALL_WORK_PROFILE=true ./install
